# Generated by Django 3.2 on 2023-05-13 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocomment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='end',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 11, 16, 8, 749601)),
        ),
    ]
